name: roadresq
description: RoadResQ - Smart Roadside Assistance App for Sri Lanka

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  

  # For persistent storage (used in Our Services screen)
  shared_preferences: ^2.3.2

  image_picker: ^1.2.1
  firebase_core: ^3.6.0           # keep or update to 3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0

  ggoogle_maps_flutter: ^2.5.0
  geolocator: ^10.0.0 # map for provider to confirm location
  geocoding: ^2.1.1
  http: ^1.2.0
  url_launcher: ^6.2.6
  flutter_polyline_points: ^2.0.0
  permission_handler: ^12.0.1

  cloud_firestore: ^5.4.4  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Recommended for linting and good practices

flutter:

  # Enables Material Design icons
  uses-material-design: true

  # Declare your image assets here (make sure files exist in assets/images/)
  assets:
    - assets/images/mechanic.jpg
    - assets/images/garage.jpg
    - assets/images/ongoing.jpg
    - assets/images/calendar.jpg
    - assets/images/service.jpg

  # If you add more assets later (fonts, other images, etc.), add them here
  # fonts:
  #   - family: SomeFont
  #     fonts:
  #       - asset: fonts/SomeFont-Regular.ttf